sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TSUNCZ9bCio3337wgE9wo0fMwBXDNGeoFJcKXjGbpQoxIqpqd6Y7V8qCjiYziAENpaahWFTwU1jmZk5VuVH0Tcz8XjLFTNx46bnCpPK9m7I0mZwkhwjfMSvnNm6ESWFvq+R6i3hoVBdypMKhduY6bnfLeo4HERmNCtUyka3dBytdN2dsOfx5AUM8SRZqTqW6/ciQz5zdqJXF4/ovAOzYRgNZriTf0pZ/8B0iY993m6/VfMa+m1WmnC8NVmZP+87xcVhSTJcmIvGrVgS3hbXYo3S9MFovzrR39fpbV8Tn8WLh0dHtMdT9G5OA8ElAX2Wapus56MsZZRpMsYanXNj7licQb9BjafBGPuIcYpvR0hKUNKSEJfb745z4amXvUwoNUmmstrAiQZb2bltfeVovpShO5PPyfk2zRmbeMEPgNh8RcVRF7CMYOIZb/PgMtmejmgrrhpqPJv0BM13WmzXl6BBQZjqpUSFM0EuySrLLLZB1ASPTKBWaka0sIii+WB1hz20oOyY3XMHQexpPwRk1P26n44Y0qejQGK/S1jEk3FWUGyRhPXXBInVx6DXGmKoANuVgnLrc6PYjA7ooG0bOlOo+B5Fci/KYsbQimaPBj9osFprsgpGaLaloWn0yyhASkgTVuLhcxuJcohlJyBAfNRPbT3I9scLWGA7eGznlaIQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Nature-of-Goodness_6101
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy